language: go
sudo: false

go:
    - 1.5
    - 1.6
    - tip
before_install:
  - export PATH=$PATH:$GOPATH/bin
  - go get golang.org/x/tools/cmd/vet
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/modocache/gover
  - go get github.com/mattn/goveralls

install:
  - go get -t -v ./...

script:
    - go test -coverprofile=echo.coverprofile
    - go test -coverprofile=middleware.coverprofile ./middleware
    - go test -coverprofile=engine_standatd.coverprofile ./engine/standard
    - go test -coverprofile=engine_fasthttp.coverprofile ./engine/fasthttp
    - $HOME/gopath/bin/gover
    - $HOME/gopath/bin/goveralls -coverprofile=gover.coverprofile -service=travis-ci
matrix:
  allow_failures:
    - go: tip
